// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plbgatmflvzbtjkvudhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYmdhdG1mbHZ6YnRqa3Z1ZGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2Njc4OTgsImV4cCI6MjA3NTI0Mzg5OH0.GREVBwm2JGkRTQn9LB-M92qvKrJpm4isE2vBO-REBzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});